# Generated by Django 4.2.3 on 2023-08-07 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passwordManager', '0002_rename_accounts_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_first_name', models.CharField(max_length=250)),
                ('admin_last_name', models.CharField(max_length=250)),
                ('admin_user_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_url', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=250)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passwordManager.admin')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passwordManager.platform')),
            ],
        ),
    ]
