# Generated by Django 4.2.3 on 2023-08-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordManager', '0004_account_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='token',
            name='platform',
        ),
        migrations.AddField(
            model_name='platform',
            name='instance_url',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='platform',
            name='token',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_link',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
