# Generated by Django 4.2.3 on 2023-08-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordManager', '0005_remove_token_admin_remove_token_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='instance_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='platform',
            name='token',
            field=models.CharField(default='', max_length=250),
        ),
    ]
