# Generated by Django 4.2.3 on 2023-08-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordManager', '0007_alter_platform_instance_url_alter_platform_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='instance_url',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='platform',
            name='token',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
