# Generated by Django 4.2.3 on 2023-08-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordManager', '0010_platform_api_login_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='api_login_password',
            field=models.CharField(blank=True, default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='platform',
            name='api_login_username',
            field=models.CharField(blank=True, default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='None', max_length=255),
        ),
    ]
