# Generated by Django 4.2.3 on 2023-08-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordManager', '0011_alter_platform_api_login_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='api_login_password',
            field=models.CharField(blank=True, default='None', max_length=250),
        ),
    ]
