# Generated by Django 4.2.3 on 2023-08-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwordManager', '0012_account_user_id_on_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_id_on_platform',
        ),
    ]
