# Generated by Django 4.2.3 on 2023-08-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwordManager', '0013_alter_platform_api_login_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='api_login_password',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='api_login_username',
        ),
    ]
