# Generated by Django 4.2.3 on 2023-08-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordManager', '0014_account_user_id_on_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id_on_platform',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
